Initial commit
ramizhub/duplicate_checker pull request #1
Opened 2022-05-30 21:21 UTC by ramizhub

2022-06-16 07:24 UTC, suletm requested changes

2022-06-16 07:24 UTC, suletm commented on duplicate_checker.c
> +                    } while(sum_bytes != sizeof(int));
There seems to be a bug in this loop (lines 102-109). Assuming sizeof(int) is 4 bytes, imagine while read()-ing, a signal was received and it returned processed_bytes = 2.  Then the loop will restart and read() will attempt to read another 4 bytes and will succeed then. In total it will be 6 bytes read from the pipe.  Your retry logic needs to account for remaining number of bytes instead of trying to read the whole thing again.

2022-06-16 07:24 UTC, suletm commented on duplicate_checker.c
> +                    int task_length;
Can task length be negative ? If not, then unsigned int would be a better choice of the type.

2022-06-16 07:24 UTC, suletm commented on duplicate_checker.c
> +                    } while(sum_bytes != sizeof(char) * task_length);
Same problem with the loop. Account for remaining bytes.

2022-06-16 07:24 UTC, suletm commented on duplicate_checker.c
> +                    } while(sum_bytes != sizeof(int));
Same problem with the loop

2022-06-16 07:24 UTC, suletm commented on duplicate_checker.c
> +                    } while(sum_bytes != sizeof(char) * task_length);
Same problem with the loop

2022-06-16 07:24 UTC, suletm commented on duplicate_checker.c
> +                    } while(sum_bytes != sizeof(unsigned char) * hash_length);
Same problem with the loop

2022-06-16 07:24 UTC, suletm commented on duplicate_checker_library.h
> +        show_debug_info("copy_in_string", "bad strings copying", dest, src, -1);
"destination and source strings can not be NULL" is a more useful output

2022-06-16 07:24 UTC, suletm commented on duplicate_checker_library.h
> +    if(dest_length + src_length + 1 <= PATH_MAX)
How about the important case when dest_length < src_length ?

2022-06-16 07:24 UTC, suletm commented on duplicate_checker_library.h
> +int copy_in_string(char * dest, char * src, int dest_length, int src_length)
Write a short description for this function

2022-06-16 07:24 UTC, suletm commented on duplicate_checker_library.h
> +int make_sha256_hash(char * task, unsigned char * hash_target)
Function arguments need to be generic. In this case the first argument should be named char *path, because this function does not know about tasks. It should just operate on paths.

2022-06-16 07:24 UTC, suletm commented on duplicate_checker.c
> +                    make_sha256_hash(task, sha256_hash);
This function can return -1 to indicate an error. You should be handling it here.

2022-06-21 19:32 UTC, ramizhub commented on duplicate_checker.c
> +    show_debug_info("main", "count of processes has been reduced by one", "count of processes now", "", process_count);
Done.

2022-06-21 20:04 UTC, ramizhub commented on duplicate_checker.c
> +                    int task_length;
Done.

2022-06-21 20:17 UTC, ramizhub commented on duplicate_checker_library.h
> +int make_sha256_hash(char * task, unsigned char * hash_target)
Done.

2022-06-21 20:22 UTC, ramizhub commented on duplicate_checker.c
> +                    make_sha256_hash(task, sha256_hash);
Done.

2022-06-21 20:25 UTC, ramizhub commented on duplicate_checker_library.h
> +        show_debug_info("copy_in_string", "bad strings copying", dest, src, -1);
Done.

2022-06-21 20:38 UTC, ramizhub commented on duplicate_checker.c
> +                    } while(sum_bytes != sizeof(int));
How about reading one byte at each iteration and condition will look like ( sum_bytes < sizeof(int) ) ?

2022-06-21 21:21 UTC, ramizhub commented on duplicate_checker_library.h
> +    if(dest_length + src_length + 1 <= PATH_MAX)
Is this really necessary? I'm just checking whether these two strings will fit in this array. In fact, I didn't specify that PATH_MAX is the size of all string arrays.

2022-06-22 01:45 UTC, suletm commented on duplicate_checker_library.h
> +    if(dest_length + src_length + 1 <= PATH_MAX)
What will happen if the buffer where dest is pointing to is smaller than the src_length ?

2022-06-23 08:34 UTC, ramizhub commented on duplicate_checker.c
> +                    } while(sum_bytes != sizeof(int));
Done. Now the read function knows about the number of remaining bytes.

2022-06-23 08:35 UTC, ramizhub commented on duplicate_checker.c
> +                    } while(sum_bytes != sizeof(char) * task_length);
Done.

2022-06-23 08:35 UTC, ramizhub commented on duplicate_checker.c
> +                    } while(sum_bytes != sizeof(unsigned char) * hash_length);
Done.

2022-06-23 08:39 UTC, ramizhub commented on duplicate_checker_library.h
> +    if(dest_length + src_length + 1 <= PATH_MAX)
This cannot happen, all rows have the same size - PATH_MAX.

2022-06-23 08:40 UTC, ramizhub commented on duplicate_checker_library.h
> +    if(dest_length + src_length + 1 <= PATH_MAX)
Or I don't know something.

2022-06-24 03:59 UTC, suletm requested changes

2022-06-24 03:59 UTC, suletm commented on duplicate_checker.c
>                              return -1;
You probably need EXIT_FAILURE for consistency ? Same thing for a few more places later in this file.

2022-06-24 03:59 UTC, suletm commented on duplicate_checker_library.h
> +    if(dest_length + src_length + 1 <= PATH_MAX)
main() calls accept_arguments(....., folder_name[PATH_MAX]). Inside of accept_arguments() you call copy_in_string() with the destination set to the folder_name. However the source of the copy_in_string() argument is provided by the user from the command line with the -f argument. So if user specifies -f a_really_long_folder_name it will overwrite the folder_name array ? 

I haven't checked other cases when copy_in_string() is called, so unsure if this is only a problem in a single place or not.

But in general, if you are implementing a library function (which you do, because this is part of the duplicate_checker_library.h) then you need to be more defensive in the way you process arguments. Even though you assume they are checked by the caller, some time in future someone will forget to do it while using your library function. This approach makes your library function more durable against potential misuse.

Does it make sense now ?

2022-06-24 03:59 UTC, suletm commented on duplicate_checker.c
> +                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
By the way, put the link to your design doc here.

2022-06-24 03:59 UTC, suletm commented on duplicate_checker.c
> +    int pipes[process_count*2][2];
I am confused by the number of pipes. The design document says there are 2 pipes per a Master->Worker pair. You have number of pairs equal to "process_count".  So pipes[process_count][2] will initialize 2 pipes per process. Would not this be enough or am I missing something ?

2022-06-24 03:59 UTC, suletm commented on duplicate_checker_library.h
> +    char BUFFER[BUFFSIZE];
typically local variable names are not capitalized: BUFFER

2022-06-24 03:59 UTC, suletm commented on duplicate_checker_library.h
> +    show_debug_info("kill_workers", "succesfully killed all child processes", "", "", -1);
The function is defined to return int, but it does not return anything here ?

2022-06-24 03:59 UTC, suletm commented on duplicate_checker.c
> +    if(kill_workers(pids, process_count) == -1) {
Why do you kill each process more than once ? One signal should be enough.

2022-06-24 16:59 UTC, ramizhub commented on duplicate_checker.c
> +    int pipes[process_count*2][2];
I am sorry it was my mistake in design doc. We have two way communication between two processes: master and child. One pipe is not enough for us (pipe_name[2]).  We need two of them. Two pipes do look like pipes_names[2][2].  While writing this part in the design document, i was focused on the wrong numbers. It seems that everything is correct in the code the only error is in the document.

2022-06-24 17:54 UTC, ramizhub commented on duplicate_checker.c
> +                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Done.

2022-06-24 17:57 UTC, ramizhub commented on duplicate_checker_library.h
> +    char BUFFER[BUFFSIZE];
Done.

2022-06-24 18:16 UTC, ramizhub commented on duplicate_checker.c
>                              return -1;
Yes, of course! exit(EXIT_FAILURE) ends program and this is what i need, because returning -1 or something else will end only it's process, but program will work. And most likely this program will work incorrectly.

2022-06-24 18:19 UTC, ramizhub commented on duplicate_checker_library.h
> +    if(dest_length + src_length + 1 <= PATH_MAX)
I assumed that the long name, although it overflows the array, but the error will be detected immediately and does not cause problems. To be honest, i can't answer the question of how this can be fixed.

2022-06-24 18:36 UTC, ramizhub commented on duplicate_checker.c
> +    int pipes[process_count*2][2];
I figured out this issue and realized that most likely there is no error in the design document either. Every pipe has two file descriptors - one for reading and one for writing. Every pair of master and child has two pipes. pipes[process_count*2][2] is structure where we have process_count*2 pipes and every one of these pipes has two file descriptors.

2022-06-25 21:33 UTC, suletm commented on duplicate_checker.c
> +    if(kill_workers(pids, process_count) == -1) {
I see now, you are correct. Maybe you can simplify kill_workers() with size ? You don't need to pass the size, it can be computed with sizeof() on the fly.

2022-06-25 21:38 UTC, suletm requested changes
Please add your Makefile

2022-06-28 15:29 UTC, ramizhub commented on duplicate_checker.c
> +    if(kill_workers(pids, process_count) == -1) {
It seems to me that you want to reduce the number of arguments of the **kill_workers(int pids[], int limit)** function to one, but unfortunately i have not found a way to do this. You suggested the idea of applying **sizeof()** to an array that would be the only argument in the function. And with it, the function would understand where the limit is. I ran a test and the external function can not apply **sizeof()** to the array that **main()** sends to it, because for it it is a pointer to an array. It would look something like this - **sizeof(int*)**, etc. You can see more details here - shorturl.at/itD26

2022-06-28 15:35 UTC, ramizhub commented on duplicate_checker.c
> +    if(kill_workers(pids, process_count) == -1) {
![Screenshot from 2022-06-28 19-35-24](https://user-images.githubusercontent.com/94108230/176220827-97eabd7b-62b5-407f-9cd2-f41a835df101.png)

2022-06-28 15:45 UTC, ramizhub commented on duplicate_checker.c
> +    if(kill_workers(pids, process_count) == -1) {
And about calling the function. 
```
if(kill_workers(pids, process_count) == -1) {
        show_debug_info("kill_workers", "ended program", "", "", -1);
        return -1;
    }
```
Instead of process_count, we can use the calculated size of the array. For example, **sizeof(void)/sizeof(pid[0])**. But I want to leave the challenge as it is, since the readability in the current version is better.

2022-06-28 17:11 UTC, ramizhub commented on duplicate_checker.c
> +    if(kill_workers(pids, process_count) == -1) {
I also want to discuss the int copy_in_string function(char *dest, char *src, int src_length). 
My task was to add a fourth argument, say, dest_max_size, which the function would use instead of PATH_MAX. This would make the function portable. 
Everything i wrote above for the interaction of external functions and their arguments works here as well. The problem is that some functions do not use their own strings, but only pointers to them, which were also passed to them by other functions. And then a problem pops up - the copy_in_string() function is passed not the actual size of the string, but only the size of the pointer. I did a test:

```
rhub@personal:~/coding/codepractice$ gcc simple_sizeof_test.c 
rhub@personal:~/coding/codepractice$ ./a.out
Short test. Here we have a string in the main() function, after we pass it to a separate function. 
The point of the experiment is to prove that a single function works only with a pointer to a string. 


main() function				sizeof(random_string)/sizeof(random_string[0]) - 150 
sizeof_in_extern_function()		sizeof(random_string)/sizeof(random_string[0]) - 8 


The test proved that a separate function will always deal with a pointer to a string. Pointers in C have a size of 8 bytes.
```

2022-06-28 17:17 UTC, ramizhub commented on duplicate_checker.c
> +    if(kill_workers(pids, process_count) == -1) {
I will show you an example of our program:

`int accept_arguments(int argc, char * const argv[], int * process_count, int * task_per_worker, char * folder_name)`

```
case 'f':
                if(optarg != NULL)
                    if(copy_in_string(folder_name, optarg, strlen(optarg)) == -1)
                        return -1;
                break;
```
accept_arguments() does not have any of its own lines. All his work with them is actually working with pointers. It is for this reason that this function can not know about the maximum size of the dest to check in the if condition.

2022-06-28 17:41 UTC, suletm commented on duplicate_checker.c
> +    if(kill_workers(pids, process_count) == -1) {
You are right about sizeof(). The function indeed receives the pointer which will be always of fixed size. 

copy_in_string discussion does not belong in this thread, let's move it to its own thread above.

2022-06-28 17:47 UTC, suletm requested changes

2022-06-28 17:48 UTC, ramizhub commented on duplicate_checker.c
> +                        processed_bytes = read(pipes[mwcr][0], &task_length, left_count);
Unfortunately, i have not taken up looked atthis moment yet, but i remember about it.

2022-06-29 08:21 UTC, ramizhub commented on duplicate_checker.c
> +                        processed_bytes = read(pipes[mwcr][0], &task_length, left_count);
I couldn't handle the int problem (I think so).
The only idea that came to mind:

```
do {
                        processed_bytes = read(pipes[mwcr][0], &task_length + sum_bytes, left_count);
.....
.....
.....
.........}
**/* uint32_t ntohl(uint32_t netlong); */**
ntohl(task_length);
```

2022-07-02 01:56 UTC, suletm commented on duplicate_checker.c
> +                        processed_bytes = read(pipes[mwcr][0], (unsigned char *)&task_length + sum_bytes, left_count);
unsigned char and char have the same size of 1 byte (at least on x86_64 architecture), so you can avoid typing the extra " unsigned" word. Otherwise looks good to me.

2022-07-02 01:57 UTC, suletm commented on duplicate_checker.c
> +                        processed_bytes = read(pipes[mwcr][0], &task_length, left_count);
Closing this discussion thread as this was solved in your latest commit.

2022-07-02 01:59 UTC, suletm commented on duplicate_checker_library.h
> +    show_debug_info("kill_workers", "succesfully killed all child processes", "", "", -1);
As we chatted about it offline, renaming the "limit" to "size" would make this function more readable. This is just a nitpick and is not a blocker for merge. Resolving this comment.

2022-07-02 02:03 UTC, suletm commented on duplicate_checker_library.h
> +    if(dest_length + src_length + 1 <= PATH_MAX)
This looks like was fixed in one of the commits. I see you are checking the source length. Closing this discussion as the feedback  because the overflow condition is not happening anymore, but refactoring the function to be more general is not a blocker for the merge.

2022-07-02 02:06 UTC, suletm commented on duplicate_checker.c
> +    int pipes[process_count*2][2];
Ok, after taking another look I realized the communication between master and workers is bidirectional. This makes sense now. Thanks for the explanation.

2022-07-02 09:26 UTC, ramizhub commented on duplicate_checker.c
> +                        processed_bytes = read(pipes[mwcr][0], (unsigned char *)&task_length + sum_bytes, left_count);
to be honest i just wanted to show that it is exactly one byte. there is really no difference between them

2022-07-02 16:22 UTC, merged